spring:
    application:
        name: budget-buddy-account-service

server:
    port: 8080

# eureka:
#     client:
#         service-url:
#             defaultZone: http://localhost:8761/eureka
#     instance:
#         leaseRenewalIntervalInSeconds: 30
